spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/chinstagram?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: landvibe
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false