spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/chinstagram?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: landvibe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update