spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chinstagram?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: landvibe
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true